spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:online_bank
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8080
